### ISSUE TITLE
ios未启用监听时调用discover导致程序崩溃

### ISSUE THREAD

**Issue by dduanbj** [c1394393468/XiaoAnBLE#1]
设备：iphone 6s (12.2)
在未进行监听初始化时，调用`startDiscoverToPeripherals`方法直接导致crash

**Comment by c1394393468** [comment]
Hi ~ Keira , 

非常感谢你的反馈，我已经发现了这些问题，并且对SDK进行了更新，请更新SDK 至 1.0.2 后使用。
